### ISSUE TITLE
Updating User Information 

### ISSUE THREAD

**Issue by uaemmcgill** [uaem-na/donations-tracker#21]
Could there be a feature on the "My Account" page (see issue "Pages") where users can update their information? Also, could we design it so that when an update is done, the admin would have to approve the updated information (similar to when the user registers the first time)?

**Comment by uaemmcgill** [comment]
Should we make it so that although it is possible for users to update their information, they can't change whether they are registered as an individual/organization? There are so many differences between an individual/organization, that I'm assuming it'll also be difficult to coordinate that switch from the back-end.

**Comment by shjryan** [comment]
I think we should allow them to update their information. As it stands, the app only allows users to update their name. More properties will need to be included.

We should have a discussion regarding how the project team plans to tackle organizations and the administration process.

- do we want organizations to have multiple users?
- what happens if the user email that a organization account used becomes inaccessible? e.g. employee turnover

If UAEM project team manages a list of 'supported' organizations instead and we could allow individual accounts to "request to join" the said organizations. Lmk what you think.
